App\Form\Model\ProductDto:
    properties:
        type:
            - NotBlank: ~
            - Length:
                  min: 3
                  max: 250
                  minMessage: 'The type must be at least {{ limit }} characters long'
                  allowEmptyString: false
        name:
            - NotBlank: ~
            - Length:
                  min: 3
                  max: 250
                  minMessage: 'The name must be at least {{ limit }} characters long'
                  allowEmptyString: false
        description:
            - NotBlank: ~
            - Length:
                  min: 3
                  max: 250
                  minMessage: 'The description must be at least {{ limit }} characters long'
                  allowEmptyString: false
        weight:
            - NotBlank: ~
            - Length:
                  min: 3
                  max: 250
                  minMessage: 'The weight must be at least {{ limit }} characters long'
                  allowEmptyString: false